version: '3.3'

services:
  db:
    image: bitnami/mongodb:3
    container_name: 'tw-radar-db'
    environment:
      - MONGODB_ROOT_PASSWORD=adminDB
      - MONGODB_USERNAME=radar
      - MONGODB_PASSWORD=radarDB
      - MONGODB_DATABASE=radar
    ports:
      - 27017:27017
    networks:
      - db-tier

  db-admin:
    image: mongo-express
    container_name: 'tw-admin-mongo'
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=db
      #- ME_CONFIG_BASICAUTH_USERNAME=governanca.dias
      #- ME_CONFIG_BASICAUTH_PASSWORD=Dataprev00!
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=adminDB
    depends_on:
      - db
    networks:
      - db-tier

networks:
  db-tier: